import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {HEADERS,demoRows} from '../dist/core.mjs';
const {chromium}=await import(process.env.CODEFORGE_PLAYWRIGHT_PATH||'playwright');
const ctx={Buffer};vm.runInNewContext(fs.readFileSync(new URL('../dist/vendor/xlsx.full.min.js',import.meta.url),'utf8'),ctx);const XLSX=ctx.XLSX;
const artifactDir=process.env.CODEFORGE_QA_DIR||'qa';fs.mkdirSync(artifactDir,{recursive:true});
const xlsx=(rows,modify)=>{const wb=XLSX.utils.book_new(),sheet=XLSX.utils.aoa_to_sheet(rows);sheet['!cols']=[{wch:22},{wch:30},{wch:18}];if(modify)modify(sheet,wb);XLSX.utils.book_append_sheet(wb,sheet,'Marks');return Buffer.from(XLSX.write(wb,{type:'array',bookType:'xlsx'}));};
fs.writeFileSync(new URL('../dist/sample-marks.xlsx',import.meta.url),xlsx(demoRows()));
const browser=await chromium.launch({headless:true,...(process.env.CODEFORGE_CHROME_PATH?{executablePath:process.env.CODEFORGE_CHROME_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1080},acceptDownloads:true});
const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
async function check(name,fn){await fn();results.push(name);console.log('PASS '+name);}
async function upload(rows,name='marks.xlsx',modify){await page.locator('#file').setInputFiles({name,mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:xlsx(rows,modify)});await page.waitForFunction(()=>!document.querySelector('#file').disabled);}
async function replace(){const before=await page.locator('#file-status').textContent();await page.locator('#confirm-action').click();await page.waitForFunction(old=>document.querySelector('#file-status').textContent!==old,before);}
try{
 await page.goto('http://127.0.0.1:4173');
 await check('empty-state controls safe and XLSX picker correct',async()=>{assert.equal(await page.locator('#review').isDisabled(),true);assert.equal(await page.locator('#reset').isDisabled(),true);assert.ok((await page.locator('#file').getAttribute('accept')).includes('.xlsx'));assert.equal(await page.locator('#timer').textContent(),'00:00');});
 await page.screenshot({path:path.join(artifactDir,'desktop-empty.png'),fullPage:true});
 await check('template downloads with three correct headers',async()=>{const event=page.waitForEvent('download');await page.locator('#template').click();const d=await event;const wb=XLSX.read(fs.readFileSync(await d.path(),'binary'),{type:'binary'});assert.deepEqual(Array.from(XLSX.utils.sheet_to_json(wb.Sheets.Marks,{header:1})[0]),HEADERS);});
 await check('demo shows correct statistics and unique courses',async()=>{await page.locator('#demo').click();assert.equal(await page.locator('#stat-count').textContent(),'48');assert.equal(await page.locator('#stat-range').textContent(),'18 / 100');assert.equal(await page.locator('#course option').count(),2);assert.equal(await page.locator('#review').isDisabled(),true);await page.locator('#instructor').fill('Dr. Sample');assert.equal(await page.locator('#review').isEnabled(),true);});
 await page.screenshot({path:path.join(artifactDir,'desktop-demo.png'),fullPage:true});
 await check('invalid cutoffs block export; undo restores validity',async()=>{await page.locator('#cutoff-0').fill('70');assert.equal(await page.locator('#review').isDisabled(),true);assert.match(await page.locator('#range-error').textContent(),/lower/);await page.locator('#undo').click();assert.equal(await page.locator('#cutoff-0').inputValue(),'80');assert.equal(await page.locator('#review').isEnabled(),true);});
 await check('course drafts persist separately and show grade impact',async()=>{await page.locator('#cutoff-0').fill('79');assert.match(await page.locator('#impact-label').textContent(),/^1 student/);await page.locator('#course').selectOption('Linear Algebra');assert.equal(await page.locator('#cutoff-0').inputValue(),'80');await page.locator('#course').selectOption('Data Structures');assert.equal(await page.locator('#cutoff-0').inputValue(),'79');});
 await check('student search, grade filter, sorting and pagination',async()=>{await page.locator('#search').fill('DEMO0048');assert.equal(await page.locator('#student-body tr').count(),1);assert.match(await page.locator('#student-body').textContent(),/100 \/ 100/);await page.locator('#search').fill('');await page.locator('#grade-filter').selectOption('E');assert.equal(await page.locator('#student-body tr').count(),1);await page.locator('#grade-filter').selectOption('');await page.locator('#sort').selectOption('high');assert.match(await page.locator('#student-body tr').first().textContent(),/100 \/ 100/);await page.locator('#next').click();assert.equal(await page.locator('#page-label').textContent(),'11–20 of 48 students');});
 await check('CSV and audit exports include every course student despite filters',async()=>{await page.locator('#search').fill('DEMO0048');await page.locator('#review').click();assert.equal(await page.locator('#export-count').textContent(),'48');await page.screenshot({path:path.join(artifactDir,'export-review.png'),fullPage:false});const event=page.waitForEvent('download');await page.locator('#download').click();const d=await event;const csv=fs.readFileSync(await d.path(),'utf8');assert.equal(csv.trim().split('\r\n').length,49);assert.match(csv,/"DEMO0001"/);assert.equal(d.suggestedFilename(),'Data-Structures-grades.csv');const event2=page.waitForEvent('download');await page.locator('#audit').click();const audit=JSON.parse(fs.readFileSync(await (await event2).path(),'utf8'));assert.equal(audit.studentCount,48);assert.equal(audit.gradeBands[0].min,79);await page.keyboard.press('Escape');});
 await check('timer resumes after editing exported grades',async()=>{await page.locator('#cutoff-0').fill('80');const before=await page.locator('#timer').textContent();await page.waitForTimeout(1100);assert.notEqual(await page.locator('#timer').textContent(),before);});
 await check('reset uses one confirmation and is undoable',async()=>{await page.locator('#cutoff-0').fill('79');await page.locator('#reset').click();assert.match(await page.locator('#confirm-title').textContent(),/Reset/);await page.locator('#confirm-action').click();await page.waitForFunction(()=>document.querySelector('#cutoff-0').value==='80');assert.equal(await page.locator('#cutoff-0').inputValue(),'80');await page.locator('#undo').click();assert.equal(await page.locator('#cutoff-0').inputValue(),'79');});
 await check('actual XLSX import clears stale courses and preserves zero and 100',async()=>{await upload([HEADERS,['001','New Course',0],['002','New Course',100],['003','Other Course',50]]);await replace();assert.equal(await page.locator('#course option').count(),2);assert.equal(await page.locator('#course').inputValue(),'New Course');assert.equal(await page.locator('#stat-range').textContent(),'0 / 100');assert.equal(await page.locator('#stat-mean').textContent(),'50');assert.match(await page.locator('#student-body').textContent(),/001/);});
 await check('invalid rows report worksheet numbers and preserve current workbook',async()=>{await upload([HEADERS,['001','Wrong',80.2],['002','Wrong','NC']],'invalid.xlsx');assert.match(await page.locator('#error-list').textContent(),/Row 2/);assert.match(await page.locator('#error-list').textContent(),/Row 3/);assert.equal(await page.locator('#course').inputValue(),'New Course');assert.equal(await page.locator('#stat-count').textContent(),'2');});
 await check('formula workbook rejected',async()=>{await upload([HEADERS,['001','CS',80]],'formula.xlsx',sheet=>{sheet.C2.f='40+40';});assert.match(await page.locator('#error-list').textContent(),/C2 contains a formula/);});
 await check('corrupt workbook produces recoverable feedback',async()=>{await page.locator('#file').setInputFiles({name:'broken.xlsx',mimeType:'application/octet-stream',buffer:Buffer.from('not a spreadsheet')});await page.waitForFunction(()=>!document.querySelector('#file').disabled);assert.match(await page.locator('#error-list').textContent(),/not an .xlsx workbook/);});
 await check('replacement cancel preserves existing data',async()=>{await upload([HEADERS,['X','Cancel Course',80]]);await page.locator('#confirm-dialog button[value="cancel"]').last().click();assert.equal(await page.locator('#course').inputValue(),'New Course');});
 await check('large constant cohort histogram remains in bounds',async()=>{await upload([HEADERS,...Array.from({length:1000},(_,i)=>[`S${i}`,'Constant',70])],'constant.xlsx');await replace();assert.equal(await page.locator('#stat-count').textContent(),'1,000');assert.match(await page.locator('#insight-text').textContent(),/same mark/);const heights=await page.locator('#histogram rect').evaluateAll(els=>els.map(e=>+e.getAttribute('height')));assert.ok(Math.max(...heights)<=179);});
 await check('clearing instructor immediately blocks export',async()=>{await page.locator('#instructor').fill('');assert.equal(await page.locator('#review').isDisabled(),true);});
 await page.locator('#demo').click();await replace();await page.locator('#instructor').fill('Dr. Sample');
 await check('mobile layout and dialog fit 390 px',async()=>{await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifactDir,'mobile-demo.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#review').click();await page.screenshot({path:path.join(artifactDir,'mobile-export.png'),fullPage:false});assert.ok(await page.evaluate(()=>document.querySelector('#export-dialog').getBoundingClientRect().right<=innerWidth));await page.keyboard.press('Escape');});
 await check('200 percent text enlargement has no page overflow',async()=>{await page.setViewportSize({width:1280,height:900});await page.addStyleTag({content:':root{font-size:32px!important}'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
 assert.deepEqual(errors,[]);results.push('No uncaught browser exceptions');
 fs.writeFileSync(path.join(artifactDir,'browser-results.json'),JSON.stringify({passed:results.length,checks:results,uncaughtErrors:errors},null,2));
 console.log(`PASS ${results.length} browser checks`);
}catch(e){console.error(e.stack?.split('\n').slice(0,8).join('\n')||e.message);process.exitCode=1;}finally{await browser.close();}
